# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-08 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=30)),
                ('passWord', models.CharField(max_length=32)),
                ('nickName', models.CharField(max_length=32)),
                ('question', models.IntegerField(default=0)),
                ('answer', models.CharField(max_length=50)),
                ('levelName', models.IntegerField(default=0)),
                ('checkAdmin', models.BooleanField()),
                ('loginIP', models.CharField(max_length=20)),
                ('loginTime', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='adminGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('groupsite', models.CharField(max_length=30)),
                ('checkinfo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initdeviceid', models.CharField(max_length=32, null=True)),
                ('testformkey', models.CharField(max_length=1024, null=True)),
                ('substationid', models.CharField(max_length=32)),
                ('devicetypeid', models.CharField(max_length=32)),
                ('devicerunid', models.CharField(max_length=128, null=True)),
                ('devicename', models.CharField(max_length=200, null=True)),
                ('olinedate', models.DateField(null=True)),
                ('offlinedate', models.DateField(null=True)),
                ('devicesno', models.CharField(max_length=200, null=True)),
                ('deviceplace', models.CharField(max_length=1024, null=True)),
                ('dataindex', models.CharField(max_length=1024, null=True)),
                ('pdfkey', models.CharField(max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='deviceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentid', models.CharField(max_length=32, null=True)),
                ('pathcode', models.CharField(max_length=200, null=True)),
                ('devicetypename', models.CharField(max_length=200, null=True)),
                ('dataindex', models.CharField(max_length=1024, null=True)),
                ('dataenabled', models.IntegerField(null=True)),
                ('deviceformkey', models.CharField(max_length=1024, null=True)),
                ('testformkey', models.CharField(max_length=1024, null=True)),
                ('pdfkey', models.CharField(max_length=1024, null=True)),
                ('xlskey', models.CharField(max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='subStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substationid', models.CharField(max_length=200, null=True)),
                ('substationname', models.CharField(max_length=200, null=True)),
                ('substationadrr', models.CharField(max_length=128, null=True)),
                ('substationman', models.CharField(max_length=128, null=True)),
                ('mobile', models.CharField(max_length=128, null=True)),
                ('teloffice', models.CharField(max_length=128, null=True)),
                ('fax', models.CharField(max_length=128, null=True)),
                ('email', models.CharField(max_length=128, null=True)),
                ('dataindex', models.CharField(max_length=1024, null=True)),
                ('dataenabled', models.IntegerField(null=True)),
            ],
        ),
    ]
