# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-08 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managementSystem', '0002_logs'),
    ]

    operations = [
        migrations.CreateModel(
            name='mylogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=128)),
                ('content', models.CharField(max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='managementSystem.Admin')),
            ],
        ),
        migrations.DeleteModel(
            name='logs',
        ),
    ]
