# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-12 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementSystem', '0003_auto_20160309_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='experimentalType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(null=True)),
                ('templatePositions', models.CharField(max_length=200)),
                ('templateName', models.CharField(max_length=200, null=True)),
                ('indexKey', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
